# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.herd_repository:
        class: AppBundle\Repository\HerdRepositoryDoctrine
        arguments: ['@doctrine.orm.entity_manager']
        
    app.animal_repository:
        class: AppBundle\Repository\AnimalRepositoryDoctrine
        arguments: ['@doctrine.orm.entity_manager']
        
    app.dice_repository:
        class: AppBundle\Repository\DiceRepositoryDoctrine
        arguments: ['@doctrine.orm.entity_manager']
    
